/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.ocl.parser.antlr.internal.InternalOclParser;
import org.xtext.ocl.services.OclGrammarAccess;

public class OclParser extends AbstractAntlrParser {

	@Inject
	private OclGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOclParser createParser(XtextTokenStream stream) {
		return new InternalOclParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Start";
	}

	public OclGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OclGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
