/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.ocl.ui.internal.OclActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OclExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(OclActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		OclActivator activator = OclActivator.getInstance();
		return activator != null ? activator.getInjector(OclActivator.ORG_XTEXT_OCL_OCL) : null;
	}

}
