/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OclUiModule extends AbstractOclUiModule {

	public OclUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
