/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link OclWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractOclWebModule extends DefaultWebModule {

}
