/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class OclWebModule extends AbstractOclWebModule {
}
