/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.ocl.OclRuntimeModule;
import org.xtext.ocl.OclStandaloneSetup;
import org.xtext.ocl.ide.OclIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class OclWebSetup extends OclStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OclRuntimeModule(), new OclIdeModule(), new OclWebModule()));
	}
	
}
