/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ocl.ocl.ActualParameterList;
import org.xtext.ocl.ocl.Declarator;
import org.xtext.ocl.ocl.FeatureCallParameters;
import org.xtext.ocl.ocl.OclPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Feature Call Parameters</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ocl.ocl.impl.FeatureCallParametersImpl#getDecs <em>Decs</em>}</li>
 *   <li>{@link org.xtext.ocl.ocl.impl.FeatureCallParametersImpl#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FeatureCallParametersImpl extends MinimalEObjectImpl.Container implements FeatureCallParameters
{
  /**
   * The cached value of the '{@link #getDecs() <em>Decs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecs()
   * @generated
   * @ordered
   */
  protected Declarator decs;

  /**
   * The cached value of the '{@link #getParams() <em>Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParams()
   * @generated
   * @ordered
   */
  protected ActualParameterList params;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FeatureCallParametersImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OclPackage.Literals.FEATURE_CALL_PARAMETERS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Declarator getDecs()
  {
    return decs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDecs(Declarator newDecs, NotificationChain msgs)
  {
    Declarator oldDecs = decs;
    decs = newDecs;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OclPackage.FEATURE_CALL_PARAMETERS__DECS, oldDecs, newDecs);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDecs(Declarator newDecs)
  {
    if (newDecs != decs)
    {
      NotificationChain msgs = null;
      if (decs != null)
        msgs = ((InternalEObject)decs).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OclPackage.FEATURE_CALL_PARAMETERS__DECS, null, msgs);
      if (newDecs != null)
        msgs = ((InternalEObject)newDecs).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OclPackage.FEATURE_CALL_PARAMETERS__DECS, null, msgs);
      msgs = basicSetDecs(newDecs, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OclPackage.FEATURE_CALL_PARAMETERS__DECS, newDecs, newDecs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ActualParameterList getParams()
  {
    return params;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParams(ActualParameterList newParams, NotificationChain msgs)
  {
    ActualParameterList oldParams = params;
    params = newParams;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OclPackage.FEATURE_CALL_PARAMETERS__PARAMS, oldParams, newParams);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParams(ActualParameterList newParams)
  {
    if (newParams != params)
    {
      NotificationChain msgs = null;
      if (params != null)
        msgs = ((InternalEObject)params).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OclPackage.FEATURE_CALL_PARAMETERS__PARAMS, null, msgs);
      if (newParams != null)
        msgs = ((InternalEObject)newParams).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OclPackage.FEATURE_CALL_PARAMETERS__PARAMS, null, msgs);
      msgs = basicSetParams(newParams, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OclPackage.FEATURE_CALL_PARAMETERS__PARAMS, newParams, newParams));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OclPackage.FEATURE_CALL_PARAMETERS__DECS:
        return basicSetDecs(null, msgs);
      case OclPackage.FEATURE_CALL_PARAMETERS__PARAMS:
        return basicSetParams(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OclPackage.FEATURE_CALL_PARAMETERS__DECS:
        return getDecs();
      case OclPackage.FEATURE_CALL_PARAMETERS__PARAMS:
        return getParams();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OclPackage.FEATURE_CALL_PARAMETERS__DECS:
        setDecs((Declarator)newValue);
        return;
      case OclPackage.FEATURE_CALL_PARAMETERS__PARAMS:
        setParams((ActualParameterList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OclPackage.FEATURE_CALL_PARAMETERS__DECS:
        setDecs((Declarator)null);
        return;
      case OclPackage.FEATURE_CALL_PARAMETERS__PARAMS:
        setParams((ActualParameterList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OclPackage.FEATURE_CALL_PARAMETERS__DECS:
        return decs != null;
      case OclPackage.FEATURE_CALL_PARAMETERS__PARAMS:
        return params != null;
    }
    return super.eIsSet(featureID);
  }

} //FeatureCallParametersImpl
