/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.ocl.ocl.OclPackage;
import org.xtext.ocl.ocl.OneStringParamFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>One String Param Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OneStringParamFunctionImpl extends FunctionImpl implements OneStringParamFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OneStringParamFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OclPackage.Literals.ONE_STRING_PARAM_FUNCTION;
  }

} //OneStringParamFunctionImpl
