/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ocl.ocl.OclPackage;
import org.xtext.ocl.ocl.SimpleTypeSpecifier;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Type Specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimpleTypeSpecifierImpl extends MinimalEObjectImpl.Container implements SimpleTypeSpecifier
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleTypeSpecifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OclPackage.Literals.SIMPLE_TYPE_SPECIFIER;
  }

} //SimpleTypeSpecifierImpl
