/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.ocl.ocl.OclPackage;
import org.xtext.ocl.ocl.TwoIntegerParamFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Two Integer Param Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TwoIntegerParamFunctionImpl extends FunctionImpl implements TwoIntegerParamFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TwoIntegerParamFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OclPackage.Literals.TWO_INTEGER_PARAM_FUNCTION;
  }

} //TwoIntegerParamFunctionImpl
