/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ocl.ocl.OclPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends Name
{
} // Attribute
