/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ocl.ocl.Declarator#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.ocl.ocl.Declarator#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.ocl.ocl.OclPackage#getDeclarator()
 * @model
 * @generated
 */
public interface Declarator extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ocl.ocl.Name}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference list.
   * @see org.xtext.ocl.ocl.OclPackage#getDeclarator_Name()
   * @model containment="true"
   * @generated
   */
  EList<Name> getName();

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(SimpleTypeSpecifier)
   * @see org.xtext.ocl.ocl.OclPackage#getDeclarator_Type()
   * @model containment="true"
   * @generated
   */
  SimpleTypeSpecifier getType();

  /**
   * Sets the value of the '{@link org.xtext.ocl.ocl.Declarator#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(SimpleTypeSpecifier value);

} // Declarator
