/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal Collection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ocl.ocl.LiteralCollection#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.ocl.ocl.LiteralCollection#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see org.xtext.ocl.ocl.OclPackage#getLiteralCollection()
 * @model
 * @generated
 */
public interface LiteralCollection extends PrimaryExpression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(CollectionKind)
   * @see org.xtext.ocl.ocl.OclPackage#getLiteralCollection_Name()
   * @model containment="true"
   * @generated
   */
  CollectionKind getName();

  /**
   * Sets the value of the '{@link org.xtext.ocl.ocl.LiteralCollection#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(CollectionKind value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(ExpressionListOrRange)
   * @see org.xtext.ocl.ocl.OclPackage#getLiteralCollection_Exp()
   * @model containment="true"
   * @generated
   */
  ExpressionListOrRange getExp();

  /**
   * Sets the value of the '{@link org.xtext.ocl.ocl.LiteralCollection#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(ExpressionListOrRange value);

} // LiteralCollection
