/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Postfix Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ocl.ocl.OclPackage#getPostfixExpression()
 * @model
 * @generated
 */
public interface PostfixExpression extends EObject
{
} // PostfixExpression
