/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relational Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ocl.ocl.RelationalExpression#getExp <em>Exp</em>}</li>
 *   <li>{@link org.xtext.ocl.ocl.RelationalExpression#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see org.xtext.ocl.ocl.OclPackage#getRelationalExpression()
 * @model
 * @generated
 */
public interface RelationalExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ocl.ocl.AdditiveExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference list.
   * @see org.xtext.ocl.ocl.OclPackage#getRelationalExpression_Exp()
   * @model containment="true"
   * @generated
   */
  EList<AdditiveExpression> getExp();

  /**
   * Returns the value of the '<em><b>Op</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ocl.ocl.RelationalOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' containment reference list.
   * @see org.xtext.ocl.ocl.OclPackage#getRelationalExpression_Op()
   * @model containment="true"
   * @generated
   */
  EList<RelationalOperator> getOp();

} // RelationalExpression
