/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Two Integer Param Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ocl.ocl.OclPackage#getTwoIntegerParamFunction()
 * @model
 * @generated
 */
public interface TwoIntegerParamFunction extends Function
{
} // TwoIntegerParamFunction
