/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.ocl.ocl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Two String Param Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ocl.ocl.OclPackage#getTwoStringParamFunction()
 * @model
 * @generated
 */
public interface TwoStringParamFunction extends Function
{
} // TwoStringParamFunction
